project_id = "pbrayxmqzdxsmhqmzygc"

[functions.generateLogo]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.analyzeFood]
verify_jwt = false

[functions.analyzeProduct]
verify_jwt = false

[functions.checkProductSafety]
verify_jwt = false

[functions.generateRecipes]
verify_jwt = false

[functions.realtime-voice-chat]
verify_jwt = false

[functions.generateRecipesFromChat]
verify_jwt = true

[functions.analyzeShelfChoice]
verify_jwt = false

[functions.analyzeMenu]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.elevenlabs-session]
verify_jwt = false

[functions.adminUpsertAvatar]
verify_jwt = true

[functions.fitness-chat]
verify_jwt = false
